# nara/generation/readme_writer.py
"""
Enterprise README generator.
"""

import os


def write_readme(root: str, blueprint: str):
    content = f"""# Generated System ({blueprint})

This system was generated by **Nara Meta-System**.

## Deterministic Proof
- design/pipeline.json
- design/contracts.json
- design/system_spec.json

## Run
```bash
python workspace/main.py
"""